blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='home'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailings')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path

from mailings.apps import SendmailConfig
from mailings.views import MessageListView, MessageCreateView, MessageUpdateView, \
    MessageDetailView, MessageDeleteView, MailingCreateView, MailingUpdateView, MailingDeleteView, MailingListView, \
    MailingDetailView, ClientListView, ClientCreateView, ClientUpdateView, MailingUpdateModeratorView, \
    HomeView, ClientDetailView, ClientDeleteView, LogsListView

app_name = SendmailConfig.name


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('mailing_list', MailingListView.as_view(), name='mailing_list'),
    path('mailing_add/', MailingCreateView.as_view(), name='mailing_add'),
    path('mailing_view/<int:pk>', MailingDetailView.as_view(), name='mailing_view'),
    path('mailing_edit/<int:pk>/', MailingUpdateView.as_view(), name='mailing_edit'),
    path('mailing_mod_edit/<int:pk>/', MailingUpdateModeratorView.as_view(), name='mailing_mod_edit'),
    path('mailing_delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('message_list/', MessageListView.as_view(), name='message_list'),
    path('message_add/', MessageCreateView.as_view(), name='message_add'),
    path('message_edit/<int:pk>/', MessageUpdateView.as_view(), name='message_edit'),
    path('message_view/<int:pk>/', MessageDetailView.as_view(), name='message_view'),
    path('message_delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('client_add/', ClientCreateView.as_view(), name='client_add'),
    path('client_edit/<int:pk>', ClientUpdateView.as_view(), name='client_edit'),
    path('client_view/<int:pk>/', ClientDetailView.as_view(), name='client_view'),
    path('client_delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('logs_list/', LogsListView.as_view(), name='logs_list'),
]

users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from users.apps import UsersConfig
from users.views import UserLogoutView, UserLoginView, RegisterView, verification, UserUpdateView, get_users_list, \
    UserDeleteView

app_name = UsersConfig.name

urlpatterns = [
    path('', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(template_name='users/register.html'), name='register'),
    path('verify_message/', TemplateView.as_view(template_name='users/verify_message.html'), name='verify_message'),
    path('email/verify/<str:verify_code>', verification, name='verify'),
    path('success_verify/', TemplateView.as_view(template_name='users/success_verify.html'), name='success_verify'),
    path('invalid_verify/', TemplateView.as_view(template_name='users/invalid_verify.html'), name='invalid_verify'),
    path('users_list/', get_users_list, name='list_view'),
    path('edit/<int:pk>', UserUpdateView.as_view(), name='edit'),
    path('users_delete/<int:pk>/', UserDeleteView.as_view(), name='users_delete'),
]

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=250, verbose_name='Заголовок')
    content = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='blog/', verbose_name='изображение', **NULLABLE)
    views_count = models.IntegerField(default=0, verbose_name='количество просмотров')
    public_date = models.DateField(auto_now=True)

    def __str__(self):
        return self.title

    def __repr__(self):
        return self.title

mailings/models.py
from django.db import models
import users.models
from django.utils import timezone

import users

STATUS_CHOICES = [
    ('Создана', 'Создана'),
    ('Запущена', 'Запущена'),
    ('Завершена', 'Завершена'),
]
INTERVAL_CHOICES = [
    ('разовая', 'разовая'),
    ('ежедневно', 'ежедневно'),
    ('раз в неделю', 'раз в неделю'),
    ('раз в месяц', 'раз в месяц'),
]

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    """
    Модель Клиента
    """
    full_name = models.CharField(max_length=50, verbose_name='ФИО')
    email = models.EmailField(max_length=50, verbose_name='Email')
    comment = models.CharField(max_length=300, verbose_name='Комментарий', **NULLABLE)
    owner = models.ForeignKey(users.models.User, on_delete=models.CASCADE, null=True, verbose_name='взаимодействует с клиентом')

    def __str__(self):
        return f'{self.full_name}- {self.email}'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class Message(models.Model):
    """
    Модель сообщения
    """
    title = models.CharField(max_length=250, verbose_name='тема')
    content = models.TextField(verbose_name='содержание', **NULLABLE)

    owner = models.ForeignKey(users.models.User, on_delete=models.CASCADE, null=True, verbose_name='Владелец сообщения')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'


class Mailing(models.Model):
    """
    Модель рассылки
    """
    name = models.CharField(max_length=50, verbose_name='название рассылки', **NULLABLE)
    mail_to = models.ManyToManyField(Client, verbose_name='кому')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='сообщение', **NULLABLE)
    data_mailing = models.DateTimeField(default=timezone.now, verbose_name='Время рассылки')
    periodicity = models.CharField(default='разовая', max_length=50, choices=INTERVAL_CHOICES, verbose_name='периодичность')
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, help_text="Выберите Создана или Завершена")
    is_activated = models.BooleanField(default=True, verbose_name='активная рассылка')

    owner = models.ForeignKey(users.models.User, on_delete=models.CASCADE, null=True, verbose_name='Владелец рассылки')

    def __str__(self):
        return f'{self.data_mailing}'

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'
        permissions = [
            ('set_is_activated', 'Может отключать рассылку')
        ]


class Logs(models.Model):
    """
    Модель Logs
    """
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='рассылка', **NULLABLE)
    last_mailing_time = models.DateTimeField(auto_now=True, verbose_name='время последней рассылки')
    status = models.CharField(max_length=50, verbose_name='статус попытки', null=True)

    def __str__(self):
        return f'Отправлено: {self.last_mailing_time}, ' \
               f'Статус: {self.status}'

    class Meta:
        verbose_name = 'log'
        verbose_name_plural = 'logs'

mailings/forms.py
from django import forms
from django.forms import DateTimeInput

from mailings.models import Mailing, Message, Client


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        user = self.request.user
        super().__init__(*args, **kwargs)
        self.fields['mail_to'].queryset = Client.objects.filter(owner=user)
        self.fields['message'].queryset = Message.objects.filter(owner=user)

    class Meta:
        model = Mailing
        exclude = ('next_date', 'owner', 'is_activated',)

        widgets = {
            'start_date': DateTimeInput(attrs={'placeholder': 'ДД.ММ.ГГГГ ЧЧ:ММ:СС', 'type': 'datetime-local'}),
            'end_date': DateTimeInput(attrs={'placeholder': 'ДД.ММ.ГГГГ ЧЧ:ММ:СС', 'type': 'datetime-local'}),
        }


class MailingModeratorForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Mailing
        fields = ('is_activated',)


class MessageForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Message
        exclude = ('owner',)


class ClientForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Client
        exclude = ('owner',)

mailings/views.py
import random
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from blog.models import Blog
from mailings.forms import MailingForm, MessageForm, ClientForm, MailingModeratorForm
from mailings.models import Message, Mailing, Client, Logs
from mailings.services import get_cache_for_mailings, get_cache_for_active_mailings


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailings:mailing_list')
    extra_context = {
        'title': 'Создание рассылки'
    }

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs

    def form_valid(self, form, *args, **kwargs):
        if form.is_valid():
            new_mailing = form.save(commit=False)
            new_mailing.owner = self.request.user
            new_mailing.save()
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailings:mailing_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs

    def test_func(self):
        if self.request.user.is_staff:
            return True
        return self.request.user == Mailing.objects.get(pk=self.kwargs['pk']).owner


class MailingUpdateModeratorView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingModeratorForm
    success_url = reverse_lazy('mailings:mailing_list')
    permission_required = 'mailings.set_is_activated'


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing
    extra_context = {
        'title': 'Список рассылок'
    }


class HomeView(ListView):
    model = Mailing
    template_name = 'mailings/home.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['mailings_count'] = get_cache_for_mailings()
        context_data['active_mailings_count'] = get_cache_for_active_mailings()
        blog_list = list(Blog.objects.all())
        random.shuffle(blog_list)
        context_data['blog_list'] = blog_list[:3]
        context_data['clients_count'] = len(Client.objects.all())
        return context_data


class MailingDetailView(DetailView):
    model = Mailing

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['clients'] = list(self.object.mail_to.all())
        context_data['logs'] = list(Logs.objects.filter(mailing=self.object))
        return context_data


class MailingDeleteView(DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailings:ling_list')


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailings:message_list')
    extra_context = {
        'title': 'Создание сообщения'
    }

    def form_valid(self, form):
        new_message = form.save()
        new_message.owner = self.request.user
        new_message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm

    def get_success_url(self):
        return reverse('mailings:message_view', args=[self.kwargs.get('pk')])


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    extra_context = {
        'title': 'Список сообщений'
    }

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = Message.objects.filter(owner=self.request.user)
        return queryset


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('mailings:message_list')


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    extra_context = {
        'title': 'Список клиентов'
    }

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = Client.objects.filter(owner=self.request.user)
        return queryset


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailings:client_list')
    extra_context = {
        'title': 'Добавить клиента'
    }

    def form_valid(self, form):
        new_client = form.save()
        new_client.owner = self.request.user
        new_client.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailings:client_list')

    def test_func(self):
        return self.request.user == Client.objects.get(pk=self.kwargs['pk']).owner


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailings:client_list')


class LogsListView(LoginRequiredMixin, ListView):
    model = Logs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Отчет по рассылкам"
        context['log_list'] = Logs.objects.all()
        return context

mailings/templates/mailings/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SendMailService</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Сервис рассылок</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'mailings:home' %}">На главную</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'mailings:mailing_list' %}">Рассылки</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'mailings:message_list' %}">Сообщения</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'mailings:client_list' %}">Клиенты</a>
        {% if perms.sendmail.set_is_active %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:list_view' %}">Пользователи</a>
        {% endif %}
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
        {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>

    {% block content %}
    {% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
            </div>
        </div>
</footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

mailings/templates/mailings/client_confirm_delete.html
{% extends 'mailings/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить клиента "{{ object.full_name }}"?</p>
                            <button type="submit" class="btn btn-primary">Подтвердить</button>
                            <a href="{% url 'mailings:client_list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailings/templates/mailings/client_detail.html
{% extends 'mailings/base.html' %}
{% block content %}
<div class="header mx-auto text-center">
    <h5 class="display-4">{{ title }}</h5>
</div>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'mailings:client_add' %}">Добавить клиента</a>
</div>
<div class="col-12">
    <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="my-0 font-weight-normal">{{ object.full_name|title }}</h3>
                    </div>
                    <div class="card-body">
                        <p>{{ object.email }}</p>
                        {% if object.comment %}
                            <p>{{ object.comment }}</p>
                        {% endif %}
                         <a href="{% url 'mailings:client_edit' object.pk %}"
                               class="btn btn-sm btn-outline-primary">Редактировать</a>
                            <a href="{% url 'mailings:client_delete' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-danger">Удалить</a>
                    </div>
                </div>
            </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/client_form.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="header mx-auto text-center">
    <h5 class="display-4">{{ title }}</h5>
</div>
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        {% if object %}
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                        {% else %}
                            <button type="submit" class="btn btn-primary">Создать</button>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/client_list.html
{% extends 'mailings/base.html' %}
{% block content %}
<div class="header mx-auto text-center">
    <h5 class="display-4">{{ title }}</h5>
</div>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'mailings:client_add' %}">Добавить клиента</a>
</div>
<div class="col-12">
    <div class="row">
        {% for object in object_list %}
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="my-0 font-weight-normal">{{ object.full_name|title }}</h3>
                    </div>
                    <div class="card-body">
                        <p>{{ object.email }}</p>
                        {% if object.comment %}
                            <p>{{ object.comment }}</p>
                        {% endif %}

                        <a href="{% url 'mailings:client_edit' object.pk %}"
                           class="btn btn-sm btn-outline-secondary">Редактировать</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

mailings/templates/mailings/home.html
{% extends 'mailings/base.html' %}
{% load my_tags %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h3 class="display-4">Сервис рассылок</h3>
    <p class="lead">Сервис управления рассылками, администрирования и получения статистики.
    </p>
</div>
<div class="container">
    <div class="col-12">
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            <div class="col-4">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Всего рассылок в сервисе</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{ mailings_count }}</h1>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Всего активных рассылок</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{ active_mailings_count }}</h1>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Число уникальных клиентов</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{ clients_count }}</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        {% for blog in blog_list %}
            <div class="col-6">
                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">

                        <h3 class="mb-0">{{ blog.title }}</h3>
                        <div class="card shadow-sm">
                         <img src="{{ blog.preview|my_media }}" class="d-block w-100" alt="...">
                        <div class="card-body">
                        <div class="mb-1 text-muted">{{ blog.public_date }}</div>
                        <p class="card-text mb-auto">{{ blog.content }}</p>
                        <a href="#" class="stretched-link">Читать далее</a>
                    </div>
                    <div class="col-auto d-none d-lg-block">
                        <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img"
                             aria-label="Placeholder: Blog" preserveAspectRatio="xMidYMid slice" focusable="false">
                            <title>Placeholder</title>
                            <rect width="100%" height="100%" fill="#55595c"/>
                            <text x="50%" y="50%" fill="#eceeef" dy=".3em">Блог</text>
                        </svg>

                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

mailings/templates/mailings/logs_list.html
{% extends 'mailings/base.html' %}
{% block content %}
<div class="table">
    <table>
        <tr>
            <td>
                Время рассылки
            </td>
            <td>
                Рассылка
            </td>
            <td>
                Статус
            </td>
        </tr>
        {% for log in log_list %}
        <tr>
            <td>
                {{ log.last_mailing_time }}
            </td>
            <td>
                {{ log.mailing }}
            </td>
            <td>
                {{ log.status }}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

mailings/templates/mailings/mailing_confirm_delete.html
{% extends 'mailings/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить рассылку "{{ object.name }}"?</p>
                            <button type="submit" class="btn btn-primary">Подтвердить</button>
                            <a href="{% url 'mailings:home' %}" class="btn btn-warning">Отмена</a>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailings/templates/mailings/mailing_form.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="header mx-auto text-center">
    <h5 class="display-4">{{ title }}</h5>
</div>
<div class="col-6">
    <div class="card">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    <div class="fieldWrapper">
                        {{ field.label_tag }} {{ field }}
                        {% if field.help_text %}
                            <p class="help" id="{{ field.auto_id }}_helptext">
                                {{ field.help_text|safe }}
                            </p>
                        {% endif %}
                    </div>
                {% endfor %}

                {% if object %}
                <button type="submit" class="btn btn-primary">Сохранить</button>
                {% else %}
                <button type="submit" class="btn btn-primary">Создать</button>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/mailing_list.html
{% extends 'mailings/base.html' %}
{% block content %}
<div class="header mx-auto text-center">
    <h5 class="display-4">{{ title }}</h5>
</div>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'mailings:mailing_add' %}">Создать рассылку</a>
    <a class="btn btn-outline-primary" href="{% url 'mailings:logs_list' %}">Отчет по рассылкам</a>
</div>
<div class="col-12">
    <div class="row">

        {% for object in object_list %}
            {% if user == object.owner or perms.mailings.view_mailing %}
            <div class="col-6 mb-3">
                <div class="card">
                    <div class="card-header">
                        <h3 class="my-0 font-weight-normal">Рассылка</h3>
                    </div>
                    <div class="card-body">
                        <p>время рассылки {{ object.data_mailing }}</p>
                        <p>с периодичностью {{ object.periodicity }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <a href="{% url 'mailings:mailing_view' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-primary">Подробнее</a>

                        </div>
                        <div class="card-footer">
                            {% if object.is_activated %}
                            <p>Действующая</p>
                            {% else %}
                            <p>Отменена</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        {% endfor %}

    </div>
</div>
{% endblock %}

mailings/templates/mailings/message_confirm_delete.html
{% extends 'mailings/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить сообщение "{{ object.title }}"?</p>
                            <button type="submit" class="btn btn-primary">Подтвердить</button>
                            <a href="{% url 'mailings:message_list' %}" class="btn btn-warning">Отмена</a>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailings/templates/mailings/message_detail.html
{% extends 'mailings/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    <p>{{ object.content }}</p>
                    {% if user == object.owner %}
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'mailings:message_edit' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-secondary">Редактировать</a>
                            <a href="{% url 'mailings:message_delete' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-danger">Удалить</a>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailings/templates/mailings/message_list.html
{% extends 'mailings/base.html' %}
{% block content %}
<div class="header mx-auto text-center">
    <h5 class="display-4">{{ title }}</h5>
</div>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'mailings:message_add' %}">Создать сообщение для рассылки</a>
</div>
<div class="col-12">
    <div class="row">
        {% for object in object_list %}
        <div class="col-6 mb-3">
            <div class="card">
                <div class="card-header">
                    <h3 class="my-0 font-weight-normal">{{ object.title }}</h3>
                </div>
                <div class="card-body">
                    <p>{{ object.content }}</p>
                    <a href="{% url 'mailings:message_view' object.pk %}"
                       class="btn btn-sm btn-outline-secondary">Просмотр</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}